DROP TABLE IF EXISTS capcode CASCADE;
DROP TABLE IF EXISTS capcodetype CASCADE;
DROP TABLE IF EXISTS sqlaction CASCADE;
DROP TABLE IF EXISTS resourcetype CASCADE;
DROP SEQUENCE IF EXISTS capclass_id_gen CASCADE;
DROP VIEW  IF EXISTS ft_capclass CASCADE;
DROP TABLE IF EXISTS capclass CASCADE;
DROP TABLE IF EXISTS capclasstype CASCADE;
